name: "Terraform CI/CD"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key }}
  AWS_REGION: us-east-1

jobs:
  terraform:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Install Checkov
        run: |
          python3 -m pip install --upgrade pip
          pip install checkov

      # Run Checkov for each module in Terraform
      - name: Checkov - Static Code Analysis on EC2 Module
        run: checkov -d ec2 || true

      - name: Checkov - Static Code Analysis on Route Table Module
        run: checkov -d route_table || true

      - name: Checkov - Static Code Analysis on Security Group Module
        run: checkov -d security_group || true

      - name: Checkov - Static Code Analysis on Subnets Module
        run: checkov -d subnets || true

      - name: Checkov - Static Code Analysis on VPC Module
        run: checkov -d vpc || true

      #-----------------------------------------------------------------------

      # Initialize Terraform
      - name: Terraform Init
        id: init
        run: terraform init

      # Plan Terraform
      - name: Terraform Plan
        id: plan
        run: terraform plan

      # Apply Terraform
      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve
